config/routes.rb
Rails.application.routes.draw do
    devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: "registrations" }
    resources :jobs
    resources :users
    resources :profiles
    
    

    root 'pages#home'
    get '/work' => "pages#home", as: :work
    get '/hire' => "pages#hire", as: :hire
    get '/jobs' => "jobs#index", as: :user_root

    

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
    has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
    
    enum referral_source: {
        member: 1, 
        internet: 2, 
        magazine: 3, 
        seminar: 4,
        job_fair: 5, 
        other: 6}
    

end
    
    

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
    before_filter :authenticate_user!

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
        if  profile_validator
        @profile.update(profile_params)
            format.html { redirect_to @profile, notice: profile_params[:willing_to_relocate].to_s() + 'Profile was suiiiiccessfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
            current_user.profile_complete = true
            current_user.save
      else
            
            format.html {redirect_to edit_profile_path, notice: "Fill all fields" }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

    def profile_validator
        if current_user.roles == 'employee'
            if profile_params[:member_name].blank? ||
                    profile_params[:address].blank? ||
                    profile_params[:job_titles_held].blank? ||
                    profile_params[:skills].blank? 
            return false
            else
                return true
            end
        else if current_user.roles == 'employer'
            if profile_params[:company_name].blank? ||
                    profile_params[:company_location].blank? ||
                    profile_params[:contact_person].blank? ||
                    profile_params[:contact_number].blank? ||
                    profile_params[:billing_contact_number].blank? ||
                    profile_params[:billing_contact_person].blank? 
                return false
            else
                return true
            end
        end
        end
    end
  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:company_name, :company_location, :contact_person, :contact_number, :billing_contact_number, :billing_contact_person, :avatar_url, :member_name, :address, :job_titles_held, :skills, :willing_to_relocate, :name_of_referral, :avatar)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
 <%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<% if current_user.roles == 'employer' %>
  <div class="field">
    <%= f.label :company_name %><br>
    <%= f.text_field :company_name %>
      </div>

  <div class="field">
    <%= f.label :company_location %><br>
    <%= f.text_area :company_location %>
  </div>
  <div class="field">
    <%= f.label :contact_person %><br>
    <%= f.text_field :contact_person %>
  </div>
  <div class="field">
    <%= f.label :contact_number %><br>
    <%= f.text_field :contact_number %>
  </div>
  <div class="field">
    <%= f.label :billing_contact_number %><br>
    <%= f.text_field :billing_contact_number %>
  </div>
  <div class="field">
    <%= f.label :billing_contact_person %><br>
    <%= f.text_field :billing_contact_person %>
  </div>
<% end %> 
<% if current_user.roles == 'employee'%>
  <div class="field">
    <%= f.label 'Photo_url' %><br>
    <%= f.file_field :avatar %>
  </div>
  <div class="field">
    <%= f.label :member_name %><br>
    <%= f.text_field :member_name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :job_titles_held %><br>
    <%= f.text_area :job_titles_held %>
  </div>
  <div class="field">
    <%= f.label :skills %><br>
    <%= f.text_area :skills %>
  </div>
  <div class="field">
    <%= f.label :willing_to_relocate %><br>
    <%= f.check_box :willing_to_relocate %><br>
  </div>
  <div class="field">
      <%= f.label 'How did you hear about us?' %><br>
      <%= f.select :referral_source,  :options => Profile.referral_sources.keys.to_a %>
  </div>
  <div class="field">
    <%= f.label :name_of_referral %><br>
    <%= f.text_field :name_of_referral %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<% end %>

app/views/profiles/edit.html.erb
<div class="form-container">
<h1>Editing Profile</h1>

<%= render 'form' %>
</div>
<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<% if current_user.admin? %>

<h1>Listing Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Company name</th>
      <th>Company location</th>
      <th>Contact person</th>
      <th>Contact number</th>
      <th>Billing contact number</th>
      <th>Billing contact person</th>
      <th>Avatar url</th>
      <th>Member name</th>
      <th>Address</th>
      <th>Job titles held</th>
      <th>Skills</th>
      <th>Willing to relocate</th>
      <th>Name of referral</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.company_name %></td>
        <td><%= profile.company_location %></td>
        <td><%= profile.contact_person %></td>
        <td><%= profile.contact_number %></td>
        <td><%= profile.billing_contact_number %></td>
        <td><%= profile.billing_contact_person %></td>
        <td><%= profile.avatar_url %></td>
        <td><%= profile.member_name %></td>
        <td><%= profile.address %></td>
        <td><%= profile.job_titles_held %></td>
        <td><%= profile.skills %></td>
        <td><%= profile.willing_to_relocate %></td>
        <td><%= profile.name_of_referral %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>
<% else %>
<h1> Only admin can view this area</h1>
<% end %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<div class="profile-container">
    <%= image_tag @profile.avatar.url %>
    <%= image_tag @profile.avatar.url(:medium) %>
    <%= image_tag @profile.avatar.url(:thumb) %>
<p id="notice"><%= notice %></p>
<% if current_user.roles == 'employer' %>
<p>
  <strong>Company name:</strong>
  <%= @profile.company_name %>
</p>

<p>
  <strong>Company location:</strong>
  <%= @profile.company_location %>
</p>

<p>
  <strong>Contact person:</strong>
  <%= @profile.contact_person %>
</p>

<p>
  <strong>Contact number:</strong>
  <%= @profile.contact_number %>
</p>

<p>
  <strong>Billing contact number:</strong>
  <%= @profile.billing_contact_number %>
</p>

<p>
  <strong>Billing contact person:</strong>
  <%= @profile.billing_contact_person %>
</p>
<% end %> 
<% if current_user.roles == 'employee'%>
<p>
  <strong>Avatar url:</strong>
  <%= @profile.avatar_url %>
</p>

<p>
  <strong>Member name:</strong>
  <%= @profile.member_name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @profile.address %>
</p>

<p>
  <strong>Job titles held:</strong>
  <%= @profile.job_titles_held %>
</p>

<p>
  <strong>Skills:</strong>
  <%= @profile.skills %>
</p>

<p>
  <strong>Willing to relocate:</strong>
  <%= @profile.willing_to_relocate %>
</p>

<p>
  <strong>Name of referral:</strong>
  <%= @profile.name_of_referral %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |

</div>
<% end %>