config/routes.rb
Rails.application.routes.draw do
    devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: "registrations" }
    resources :jobs
    resources :users
    resources :profiles
    
    

    root 'pages#home'
    get '/work' => "pages#home", as: :work
    get '/hire' => "pages#hire", as: :hire
    get '/jobs' => "jobs#index", as: :user_root

    

end

app/models/job.rb
class Job < ActiveRecord::Base
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
    before_filter :authenticate_user!
   before_filter :ensure_signup_complete
  before_action :set_job, only: [:show, :edit, :update, :destroy]
    

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:title, :tagline, :description, :position, :job_type, :instructions, :skills, :prerequisites, :category, :location, :price, :employer_id)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :tagline %><br>
    <%= f.text_field :tagline %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :position %><br>
    <%= f.text_field :position %>
  </div>
  <div class="field">
    <%= f.label :job_type %><br>
    <%= f.text_field :job_type %>
  </div>
  <div class="field">
    <%= f.label :instructions %><br>
    <%= f.text_area :instructions %>
  </div>
  <div class="field">
    <%= f.label :skills %><br>
    <%= f.text_area :skills %>
  </div>
  <div class="field">
    <%= f.label :prerequisites %><br>
    <%= f.text_area :prerequisites %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_area :location %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :employer_id %><br>
    <%= f.number_field :employer_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<div class=" center">
<p id="notice"><%= notice %></p>

<h1>Listing Jobs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Tagline</th>
      <th>Description</th>
      <th>Position</th>
      <th>Job type</th>
      <th>Instructions</th>
      <th>Skills</th>
      <th>Prerequisites</th>
      <th>Category</th>
      <th>Location</th>
      <th>Price</th>
      <th>Employer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.title %></td>
        <td><%= job.tagline %></td>
        <td><%= job.description %></td>
        <td><%= job.position %></td>
        <td><%= job.job_type %></td>
        <td><%= job.instructions %></td>
        <td><%= job.skills %></td>
        <td><%= job.prerequisites %></td>
        <td><%= job.category %></td>
        <td><%= job.location %></td>
        <td><%= job.price %></td>
        <td><%= job.employer_id %></td>
        <td><%= link_to 'Show', job %></td>
        <td><%= link_to 'Edit', edit_job_path(job) %></td>
        <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user.roles=='employer' %>
<%= link_to 'New Job', new_job_path %>
<% end %>
</div>d

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @job.title %>
</p>

<p>
  <strong>Tagline:</strong>
  <%= @job.tagline %>
</p>

<p>
  <strong>Description:</strong>
  <%= @job.description %>
</p>

<p>
  <strong>Position:</strong>
  <%= @job.position %>
</p>

<p>
  <strong>Job type:</strong>
  <%= @job.job_type %>
</p>

<p>
  <strong>Instructions:</strong>
  <%= @job.instructions %>
</p>

<p>
  <strong>Skills:</strong>
  <%= @job.skills %>
</p>

<p>
  <strong>Prerequisites:</strong>
  <%= @job.prerequisites %>
</p>

<p>
  <strong>Category:</strong>
  <%= @job.category %>
</p>

<p>
  <strong>Location:</strong>
  <%= @job.location %>
</p>

<p>
  <strong>Price:</strong>
  <%= @job.price %>
</p>

<p>
  <strong>Employer:</strong>
  <%= @job.employer_id %>
</p>

<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>