config/routes.rb
Rails.application.routes.draw do
    devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: "registrations" }
    resources :jobs
    resources :users
    resources :profiles
    
    

    root 'pages#home'
    get '/work' => "pages#home", as: :work
    get '/hire' => "pages#hire", as: :hire
    get '/jobs' => "jobs#index", as: :user_root

    

end

app/views/pages/hire.html.erb
<div class="wrapper">
<div class="splash-module" id="employer-splash"> 
            <div class="center sm-content">
                <h2 class="sm-header"> Hire the experts</h2>
                <p class="sm-desc">& build a workforce of your dreams</p>
                <a class="sm-btn" href="/users/sign_up?role=1"> Hire an expert </a>
                <div class="sm-sec-btn">
                    <%= link_to('Do you want a job?', work_path) %>
                </div> 
            </div>
        </div>
        <span style="clear:both"></span>
        </div>
    <div class="wrapper-polythene">
        
    </div>
    

app/views/pages/home.html.erb
       <div class="wrapper">
        <div class="splash-module" id="employee-splash"> 
            <div class="center sm-content">
                <h2 class="sm-header"> Have you ever been financially rewarded</h2>
                <p class="sm-desc">twice for landing that position you so wanted and deserved? First, by the company who hired you? Second, by the company who introduced you to the opportunity? Connect with us mingle with others and see how this works.</p>
                <a class="sm-btn" href="/users/sign_up?role=0"> Connect With Us </a>       
            </div>
        
    <div class="wrapper-polythene">
        
    </div>
        </div>
       
       
        
<div class="splash-module" id="employer-splash"> 
            <div class="center sm-content">
                <h2 class="sm-header"> Let us help you</h2>
                <p class="sm-desc">enhance your staffing budget by providing you a financial return our solution brings to your costly permanent and contract positions. Become a part of a growing chain changing the way staffing is done. Connect with us to see just how this works.</p>
                <a class="sm-btn" href="/users/sign_up?role=1"> Connect with us </a>
	</div>

    <div class="wrapper-polythene">
        
    </div>
        </div>
	<span style="clear:both"></span>

        </div>
    
<script>
$(document).ready(function(){
  var isEmployeeSlide = true;
    
    function toggleSlide() {
        if (isEmployeeSlide) {
	$(' #employee-splash ').fadeTo(1000, 0);
	$(' #employer-splash').fadeTo(1000, 1);
            isEmployeeSlide = false;
	    } else {

	    $(' #employer-splash').fadeTo(1000, 0);
	    $(' #employee-splash').fadeTo(1000, 1);
            isEmployeeSlide = true;
        }
    }
    
    setInterval(toggleSlide, 7000);
    
    
});
</script>